name: 3D Contribution Calendar

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Mohamed-Shahata

      - name: Convert SVG to static PNG
        run: |
          sudo apt-get update -y
          sudo apt-get install -y librsvg2-bin
          rsvg-convert -w 1400 profile-3d-contrib/profile-night-rainbow.svg -o profile-3d-contrib/profile-night-rainbow.png

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f profile-3d-contrib
          git commit -m "Update 3D contribution calendar" || exit 0
          git push
